### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by myavuzokumus** [NukkitX/ProxyPass#14]
Hello there,
I am using the ProxyPass for geyserMC plugin and I need this to keep the host's ip address.
It both provides me a proxy and hides the ip address of my main server.
But it does not ping the server. MOTD does not appear because it does not ping.

It also trades slowly as it has extra features as a proxy.

Can you make an add-on that acts as a proxy only as an extra add-on?

The setting file should be as follows.
```
## Address proxy will bind to.
proxy:
  host: -
  port: 19132
## Destination server which the client will connect to.
## You are only able to join offline mode servers
destination:
  host: -
  port: 19132

legacy-ping-passthrough: true
ping-passthrough-interval: 3
```
